test_that("lazy eval functions are defunct", {
  expect_snapshot(error = TRUE, {
    add_count_()
    add_tally_()
    arrange_()
    count_()
    distinct_()
    do_()
    filter_()
    funs_()
    group_by_()
    group_indices_()
    mutate_()
    tally_()
    transmute_()
    rename_()
    rename_vars_()
    select_()
    select_vars_()
    slice_()
    summarise_()
    summarize_()
    summarise_each()
    summarise_each_()
    mutate_each()
    mutate_each_()
    summarize_each()
    summarize_each_()

  })
})
