#' colwise (standard evaluation).
#'
#' Apply one or more functions to one or more columns.
#'
#' @param tbl Input data.
#' @param calls List of function calls, generated by \code{\link{funs}}
#' @param vars List of quoted objects specifying variables to select.
#' @examples
#' # One function
#' colwise_q(iris, funs("mean"))
#' colwise_q(iris, funs("mean"), dots(Petal.Width))
#' colwise_q(iris, funs("mean"), dots(-Species))
#' colwise_q(iris, funs("mean"), dots(matches("Sepal")))
#'
#' # Two functions
#' colwise_q(iris, funs("min", "max"))
#' colwise_q(iris, funs("min", "max"), dots(Petal.Width))
#' colwise_q(iris, funs("min", "max"), dots(matches("Sepal")))
#'
#' # Alternative function specification
#' colwise_q(iris, funs(max, max(., na.rm = TRUE)))
#' colwise_q(iris, funs("mean"), dots(x))
colwise_q <- function(tbl, calls, vars = dots()) {
  stopifnot(is.fun_calls(calls))
  vars <- lapply(select_vars(tbl_vars(tbl), vars, env = parent.frame()), as.name)

  out <- vector("list", length(vars) * length(calls))
  dim(out) <- c(length(vars), length(calls))

  for (i in seq_along(vars)) {
    for (j in seq_along(calls)) {
      out[[i, j]] <- substitute_q(calls[[j]], list(. = vars[[i]]))
    }
  }

  dim(out) <- NULL
  out
}

