#' colwise (standard evaluation).
#'
#' Apply one or more functions to one or more columns.
#'
#' @param tbl Input data.
#' @param calls List of function calls, generated by \code{\link{funs}}
#' @param vars,... List of quoted objects specifying variables to select.
#' @examples
#' # One function
#' colwise(iris, funs(mean))
#' colwise(iris, funs(mean), Petal.Width)
#' colwise(iris, funs(mean), -Species)
#' colwise(iris, funs(mean), matches("Sepal"))
#'
#' # Two functions
#' colwise(iris, funs(min, max))
#' colwise(iris, funs(min, max), Petal.Width)
#' colwise(iris, funs(min, max), matches("Sepal"))
#'
#' # Alternative function specification
#' colwise(iris, funs(max(., na.rm = TRUE))
#'
#' fs <- c("min", "max")
#' colwise(iris, funs_q(fs))
#'
#' # Alternative variable specification
#' vars <- names(iris)
#' colwise_q(iris, funs(max), vars)
colwise <- function(tbl, calls, ...) {
  colwise_q(tbl, calls, dots(...))
}

#' @export
#' @rdname colwise
colwise_q <- function(tbl, calls, vars) {
  stopifnot(is.fun_calls(calls))
  vars <- lapply(select_vars(tbl_vars(tbl), vars, env = parent.frame()), as.name)

  out <- vector("list", length(vars) * length(calls))
  dim(out) <- c(length(vars), length(calls))

  for (i in seq_along(vars)) {
    for (j in seq_along(calls)) {
      out[[i, j]] <- substitute_q(calls[[j]], list(. = vars[[i]]))
    }
  }

  dim(out) <- NULL
  out
}

