#' Create a source for a DBI backend.
#'
#' `src_dbi()` allows you to construct a dplyr src for an any DBI backends.
#'
#' @param con An object that inherits from [DBI::DBIConnection-class],
#'   typically generated by [DBI::dbConnect]
#' @param auto_disconnect Should the connection be automatically closed when
#'   the src is deleted. This is useful for older DBI backends that don't
#'   clean up themselves.
#' @return An S3 object of class `src_dbi`, `src_sql`, `src`.
#' @export
#' @examples
#' if (requireNamespace("RSQLite", quietly = TRUE)) {
#'
#' con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
#' src <- src_dbi(con)
#'
#' copy_to(src, mtcars)
#'
#' DBI::dbListTables(con)
#' src
#' }
src_dbi <- function(con, auto_disconnect = FALSE) {
  # stopifnot(is(con, "DBIConnection"))
  disco <- if (isTRUE(auto_disconnect)) db_disconnector(con)

  structure(
    list(
      con = con,
      disco = disco
    ),
    class = c("src_dbi", "src_sql", "src")
  )
}

#' @param src A DBI src.
#' @param from Either a string giving the name of table in database, or
#'   [sql()] describing a derived table or compound join.
#' @param ... Included for compatibility with the generic, but otherwise
#'   ignored.
#' @export
#' @rdname src_dbi
tbl.src_dbi <- function(src, from, ...) {
  # If not literal sql, must be a table identifier
  if (!is.sql(from)) {
    from <- ident(from)
  }

  make_tbl(
    c("dbi", "sql", "lazy"),
    src = src,
    ops = op_base_remote(from, vars = db_vars(src, from))
  )
}


db_vars <- function(src, from) {
  vars <- attr(from, "vars")
  if (!is.null(vars))
    return(vars)

  con <- con_acquire(src)
  on.exit(con_release(src, con), add = TRUE)

  db_query_fields(con, from)
}


#' @export
src_desc.src_dbi <- function(x) {
  src_desc(x$con)
}

# Creates an environment that disconnects the database when it's GC'd
db_disconnector <- function(con, quiet = FALSE) {
  reg.finalizer(environment(), function(...) {
    if (!quiet) {
      message("Auto-disconnecting ", class(con)[[1]])
    }
    dbDisconnect(con)
  })
  environment()
}
