#' Override window order and frame
#'
#' These allow you to override the `PARTITION BY` and `ORDER BY` clauses
#' of window functions generated by grouped mutates.
#'
#' @param ... Variables to order by
#' @export
#' @examples
#' library(dbplyr)
#' library(dplyr, warn.conflicts = FALSE)
#'
#' set.seed(2022)
#' db <- memdb_frame(g = rep(1:2, each = 5), y = runif(10), z = 1:10)
#' db %>%
#'   window_order(y) %>%
#'   mutate(z = cumsum(y))
#'
#' set.seed(2022)
#' df <- tibble(g = rep(1:2, each = 5), y = runif(10), z = 1:10)
#' df %>%
#'   window_order(y) %>%
#'   mutate(z = cumsum(y))
#'
window_order <- function(.data, ...) {
  UseMethod("window_order")
}

#' @rdname arrange
#' @export
window_order.data.frame <- function(.data,
                               ...,
                               .by_group = FALSE,
                               .locale = dplyr_locale()) {
  arrange(.data = .data,
          ...,
          .by_group = .by_group,
          .locale = .locale )
}
